version: '3.8'
services:
  users-service:
    container_name: uapp
    image: users-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users-service
      - CONFIG_SERVER_URL=http://172.17.0.1:8888 # 리눅스 도커 호스트 브릿지
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    container_name: upost
    image: postgres:15
    environment:
      - POSTGRES_DB=users-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # 데이터 영속성 (옵션)
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  pgdata: