server:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users-service
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false