# 개발용 설정파일로 필요에 따라 수정
spring:
  cloud:
    config:
      enabled: false
  datasource:
    hikari:
      username: postgres
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
eureka:
  client:
    enabled: false
logging:
  level:
    org.springframework.boot.context.config: TRACE
jwt:
  refresh-token: ZHNrbGZqYWRrbHNmamxrZHNhZmtqbGFzZGZsaztqemxrY3h2anpjdnBvY2l4emp2ODlwajMyNDk4ZkAkQCFAJGZkZ3N6ZHNhZmFkc2Y=
  refresh-expiredTime: 7200000
  access-token: SGVsbG9AI2UzV3JvbGQhQCN9RHxkc2prZC0oOTBNeVNlY3JldCEyMyRGREcjMw==
  access-expiredTime: 1
gateway:
  key: ZGtzb2FmamRhc3BvZmphZHdzZjtsa2prbGohQCNAKClfKmpA