server:
  port: 8001
  http2:
    enabled: true
spring:
  application:
    name: users-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false